Repository LikeLion-RealTalk/realtalk-project-backend, pull requests merged in 2025-08, with the labels that each got.

#7 chore: Redis 컨테이너 및 연결 설정 추가
  build.gradle
  src/main/java/com/likelion/realtalk/global/config/RedisConfig.java
  src/main/java/com/likelion/realtalk/infra/redis/docker-compose-redis.yml
  src/main/resources/application.yml
Labels: chore

#13 Feat/#11 WebSocketConfig 추가
  build.gradle
  src/main/java/com/likelion/realtalk/global/config/WebSocketConfig.java
Labels: chore

#19 Feat/#6
  src/main/java/com/likelion/realtalk/domain/debate/api/DebateController.java
  src/main/java/com/likelion/realtalk/domain/debate/dto/AiMessageDto.java
  src/main/java/com/likelion/realtalk/domain/debate/dto/AudienceTimerDto.java
  src/main/java/com/likelion/realtalk/domain/debate/dto/DebateMessageDto.java
  src/main/java/com/likelion/realtalk/domain/debate/dto/DebateRoomDto.java
  src/main/java/com/likelion/realtalk/domain/debate/dto/SpeakerMessageDto.java
  src/main/java/com/likelion/realtalk/domain/debate/dto/SpeakerTimerDto.java
  src/main/java/com/likelion/realtalk/domain/debate/repository/DebateRedisRepository.java
  src/main/java/com/likelion/realtalk/domain/debate/service/AiService.java
  src/main/java/com/likelion/realtalk/domain/debate/service/SpeakerService.java
  src/main/java/com/likelion/realtalk/global/config/ClaudeAiConfig.java
  src/main/java/com/likelion/realtalk/global/config/RedisConfig.java
  src/main/java/com/likelion/realtalk/global/redis/RedisKeyExpiredListener.java
  src/main/java/com/likelion/realtalk/global/redis/RedisKeyUtil.java
  src/main/java/com/likelion/realtalk/infra/claude/ClaudeAiClient.java
  src/main/java/com/likelion/realtalk/infra/redis/docker-compose-redis.yml
  src/main/java/com/likelion/realtalk/infra/redis/redis.conf
  src/main/resources/application.yml
Labels: feature

#32 Feat/#27 webrtc 관련 테스트 페이지 및 기능 추가 pr 입니다.
  src/main/java/com/likelion/realtalk/domain/webrtc/config/WebRtcSocketConfig.java
  src/main/java/com/likelion/realtalk/domain/webrtc/controller/WebRtcController.java
  src/main/java/com/likelion/realtalk/domain/webrtc/handler/SignalingHandler.java
  src/main/java/com/likelion/realtalk/global/config/WebSocketConfig.java
  src/main/java/com/likelion/realtalk/global/security/config/SecurityConfig.java
  src/main/java/com/likelion/realtalk/global/security/jwt/JwtTokenFilter.java
  src/main/resources/templates/webrtc.html
Labels: feature

#112 feat : AI 잘못된 response 반환 시 retry, 토론 종료 시 debateResult에 정보 추가
  src/main/java/com/likelion/realtalk/domain/debate/dto/AiSummaryDto.java
  src/main/java/com/likelion/realtalk/domain/debate/dto/DebateResultDto.java
  src/main/java/com/likelion/realtalk/domain/debate/dto/SpeakerMessageDto.java
  src/main/java/com/likelion/realtalk/domain/debate/entity/DebateResult.java
  src/main/java/com/likelion/realtalk/domain/debate/repository/DebateResultRepository.java
  src/main/java/com/likelion/realtalk/domain/debate/service/AiService.java
  src/main/java/com/likelion/realtalk/domain/debate/service/DebateRedisService.java
  src/main/java/com/likelion/realtalk/domain/debate/service/DebateResultService.java
  src/main/java/com/likelion/realtalk/domain/debate/service/DebateRoomService.java
Labels: feature

#114 녹음 시작시 side 값 프론트로 넘겨주도록 수정
  src/main/java/com/likelion/realtalk/domain/debate/service/RecordingService.java
Labels: refactor

#117 [Hotfix]토론 결과 조회 쿼리 오류 수정
  src/main/java/com/likelion/realtalk/domain/debate/repository/DebateResultRepository.java
Labels: bug

#118 서버에 토론 결과 조회 기능 반영
  src/main/java/com/likelion/realtalk/domain/debate/repository/DebateResultRepository.java
Labels: bug

#126 [Feature]AI 요약 response에 side 추가
  src/main/java/com/likelion/realtalk/domain/debate/dto/AiSummaryDto.java
  src/main/java/com/likelion/realtalk/domain/debate/service/SpeakerService.java
Labels: feature

#127 서버에 AI 요약 reponse Side 추가 반영
  src/main/java/com/likelion/realtalk/domain/debate/dto/AiSummaryDto.java
  src/main/java/com/likelion/realtalk/domain/debate/service/SpeakerService.java
Labels: feature

#129 chore: 채팅메세지 로그 추가
  src/main/java/com/likelion/realtalk/domain/debate/api/DebateController.java
  src/main/java/com/likelion/realtalk/global/config/WebSocketConfig.java
  src/main/java/com/likelion/realtalk/global/security/jwt/JwtTokenFilter.java
Labels: chore

#134 [Feature] 청중 수 조회 API 개발
  src/main/java/com/likelion/realtalk/domain/debate/api/DebateController.java
  src/main/java/com/likelion/realtalk/domain/debate/dto/AudienceCountDto.java
  src/main/java/com/likelion/realtalk/domain/debate/repository/DebateRedisRepository.java
  src/main/java/com/likelion/realtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/likelion/realtalk/global/redis/RedisKeyUtil.java
Labels: feature

#135 [Feature] 청중 수 조회API 서버에 반영
  deploy/init/init.sql
  k6/README.md
  k6/data/audience-chat-params.js
  k6/run-local.audience-join-only.sh
  k6/run-local.audience-multi-chat.ramping-rate.sh
  k6/run-local.audience-multi-chat.ramping-vus.sh
  k6/run-prod.audience-multi-chat.sockjs.sh
  k6/tests/local.audience-chat-realistic.js
  k6/tests/local.audience-join-only.js
  k6/tests/local.audience-multi-chat.js
  k6/tests/local.audience-multi-chat.ramping-rate.js
  k6/tests/local.audience-multi-chat.ramping-vus.js
  k6/tests/local.create_and_join_scenario.js
  k6/tests/prod.audience-multi-chat.sockjs.js
  src/main/java/com/likelion/realtalk/domain/debate/api/DebateController.java
  src/main/java/com/likelion/realtalk/domain/debate/dto/AudienceCountDto.java
  src/main/java/com/likelion/realtalk/domain/debate/repository/DebateRedisRepository.java
  src/main/java/com/likelion/realtalk/domain/debate/service/DebateRoomService.java
  src/main/java/com/likelion/realtalk/global/redis/RedisKeyUtil.java
Labels: feature
